INSERT INTO public."AuthAppEmpleados_cargos"
(cargo)
VALUES('Gerente'),
('Director De Talento Humano'),
('Director De Proyectos'),
('Residente De Obra'),
('Coordinador Sst'),
('Profesional Sst'),
('Inspector Sst'),
('Maestro De Obra'),
('Almacenista'),
('Auxiliar De Almacen'),
('Oficial De Obra'),
('Ayudante De Obra'),
('Contador'),
('Auxiliar Contable'),
('Gerente De Construcciones'),
('Auxiliar De Recursos Humanos'),
('Mensajero'),
('Director De Proyectos'),
('Arquitecto'),
('Ingenierio civil'),
('Diseñador de interiores'),
('Secretaria'),
('Asesor comercial'),
('Diseñador Arquitectónico'),
('Diseñador de instalaciones y estructuras'),
('Auxiliar de Arquitectura'),
('Delineante'),
('Diseñador 3D'),
('Técnico – Operativo Aseo obras');

